---
abstract: 'Easily establish an HTTP server inside a program'
author:
  - 'motemen <motemen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.5, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Plackup
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  AnyEvent::Plackup:
    file: lib/AnyEvent/Plackup.pm
    version: 0.01
  AnyEvent::Plackup::Request:
    file: lib/AnyEvent/Plackup/Request.pm
requires:
  AnyEvent: 0
  Carp: 0
  Class::Accessor::Lite: 0
  Exporter::Lite: 0
  Plack::Request: 0
  Scalar::Util: 0
  Test::TCP: 2
  Twiggy: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/motemen/perl5-AnyEvent-Plackup/issues
  homepage: https://github.com/motemen/perl5-AnyEvent-Plackup
  repository: git://github.com/motemen/perl5-AnyEvent-Plackup.git
version: 0.01
